package com.Stefanini.desafio.entity;
public enum Pais {
    
    AFGANISTAO("Afeganistão"),
    AfricaDoSul("África do Sul"),
    Albania("Albânia"),
    Alemanha("Alemanha"),
    Andorra("Andorra"),
    Angola("Angola"),
    AntíguaEBarbuda("Antígua e Barbuda"),
    ArabiaSaudita("Arábia Saudita"),
    Argentina("Argentina"),
    Armenia("Armênia"),
    Australia("Austrália"),
    Austria("Áustria"),
    Azerbaijão("Azerbaijão"),
    Bahamas("Bahamas"),
    Bahrein("Bahrein"),
    Bangladesh("Bangladesh"),
    Barbados("Barbados"),
    Belgica("Bélgica"),
    Belize("Belize"),
    Benin("Benin"),
    BosniaEHerzegovina("Bósnia e Herzegovina"),
    Botswana("Botsuana"),
    Brasil("Brasil"),
    Brunei("Brunei"),
    Bulgaria("Bulgária"),
    BurkinaFaso("Burkina Faso"),
    Burundi("Burundi"),
    CaboVerde("Cabo Verde"),
    Camaroes("Camarões"),
    Canada("Canadá"),
    Casaquistao("Casaquistão"),
    Chade("Chade"),
    Chile("Chile"),
    China("China"),
    Chipre("Chipre"),
    Colombia("Colômbia"),
    Comores("Comores"),
    CongoBrazzaville("Congo (Brazzaville)"),
    CongoKinshasa("Congo (Kinshasa)"),
    CoreiaDoNorte("Coreia do Norte"),
    CoreiaDoSul("Coreia do Sul"),
    CostaDoMarfim("Costa do Marfim"),
    CostaRica("Costa Rica"),
    Croacia("Croácia"),
    Cuba("Cuba"),
    Dinamarca("Dinamarca"),
    Djibouti("Djibouti"),
    Dominica("Dominica"),
    Egito("Egito"),
    ElSalvador("El Salvador"),
    Equador("Equador"),
    Eritreia("Eritreia"),
    Escocia("Escócia"),
    Eslovaquia("Eslováquia"),
    Eslovenia("Eslovênia"),
    Espanha("Espanha"),
    EstadosUnidos("Estados Unidos"),
    Estonia("Estônia"),
    Essuatini("Essuatíni"),
    Etiópia("Etiópia"),
    Fiji("Fiji"),
    Filipinas("Filipinas"),
    Finlandia("Finlândia"),
    França("França"),
    Gabao("Gabão"),
    Gambia("Gambia"),
    Gana("Gana"),
    Georgia("Geórgia"),
    Granadinas("Granadinas"),
    Grecia("Grécia"),
    Guatemala("Guatemala"),
    Guine("Guiné"),
    GuineBissau("Guiné-Bissau"),
    GuineEquatorial("Guiné Equatorial"),
    Guyana("Guyana"),
    Haiti("Haiti"),
    Honduras("Honduras"),
    Hungria("Hungria"),
    Iemen("Iémen"),
    IlhasMarshall("Ilhas Marshall"),
    IlhasSalomao("Ilhas Salomão"),
    India("Índia"),
    Indonesia("Indonésia"),
    Ira("Irã"),
    Iraq("Iraque"),
    Irlanda("Irlanda"),
    Israel("Israel"),
    Italia("Itália"),
    Jamaica("Jamaica"),
    Japao("Japão"),
    Jordania("Jordânia"),
    Kuwait("Kuwait"),
    Laos("Laos"),
    Libano("Líbano"),
    Liberia("Libéria"),
    Libia("Líbia"),
    Liechtenstein("Liechtenstein"),
    Litua("Lituânia"),
    Luxemburgo("Luxemburgo"),
    Madagascar("Madagascar"),
    Malasia("Malásia"),
    Malawi("Malawi"),
    Maldivas("Maldivas"),
    Mali("Mali"),
    Malta("Malta"),
    Marrocos("Marrocos"),
    Mauricio("Maurício"),
    Mauritania("Mauritânia"),
    Mexico("México"),
    Micronesia("Micronésia"),
    Mocambique("Moçambique"),
    Mônaco("Mônaco"),
    Mongolia("Mongólia"),
    Montenegro("Montenegro"),
    Myanmar("Myanmar"),
    Namibia("Namíbia"),
    Nauru("Nauru"),
    Nepal("Nepal"),
    Nicaragua("Nicarágua"),
    Niger("Níger"),
    Nigeria("Nigéria"),
    Noruega("Noruega"),
    NovaZelandia("Nova Zelândia"),
    Oma("Omã"),
    PaisesBaixos("Países Baixos"),
    Palau("Palau"),
    Panama("Panamá"),
    PapuaNovaGuinea("Papua-Nova Guiné"),
    Paquistao("Paquistão"),
    Paraguai("Paraguai"),
    Peru("Peru"),
    Polonia("Polônia"),
    Portugal("Portugal"),
    Qatar("Qatar"),
    Quenia("Quênia"),
    ReinoUnido("Reino Unido"),
    RepublicaCentroAfricana("Rep. Centro-Africana"),
    RepublicaDemocraticaDoCongo("Rep. Democrática do Congo"),
    RepublicaDominicana("Rep. Dominicana"),
    Romania("Romênia"),
    Russia("Rússia"),
    Ruanda("Ruanda"),
    SaoCristovaoENevis("São Cristóvão e Nevis"),
    SaoTomeEPrincipe("São Tomé e Príncipe"),
    Samoa("Samoa"),
    SanMarino("San Marino"),
    SantaLucia("Santa Lúcia"),
    SaoVicenteEGranadinas("São Vicente e Granadinas"),
    Senegal("Senegal"),
    SerraLeoa("Serra Leoa"),
    Singapura("Singapura"),
    Somalia("Somália"),
    SriLanka("Sri Lanka"),
    Suazilandia("Suazilândia"),
    Sudao("Sudão"),
    SudaoDoSul("Sudão do Sul"),
    Suecia("Suécia"),
    Suica("Suíça"),
    Siria("Síria"),
    Taiwan("Taiwan"),
    Tajiquistao("Tajiquistão"),
    Tanzania("Tanzânia"),
    TimorLeste("Timor-Leste"),
    Togo("Togo"),
    Tonga("Tonga"),
    TrinidadETobago("Trinidad e Tobago"),
    Tunisia("Tunísia"),
    Turcomenistao("Turcomenistão"),
    Turquia("Turquia"),
    Tuvalu("Tuvalu"),
    Ucrania("Ucrânia"),
    Uganda("Uganda"),
    Uruguai("Uruguai"),
    Uzbequistao("Uzbequistão"),
    Vanuatu("Vanuatu"),
    Venezuela("Venezuela"),
    Vietna("Vietnã"),
    Zambia("Zâmbia"),
    Zimbabwe("Zimbábue");

    private String pais;

    private Pais(String pais){
        this.pais=pais;
    }

    public String getPais(){
        return pais;
    }
}
